const List<Map<String, String>> timezones = [
  {'label': 'UTC (Universal Coordinated Time)', 'value': 'UTC'},
  {'label': 'West Africa Time (Lagos, Kinshasa)', 'value': 'Africa/Lagos'},
  {'label': 'Central Africa Time (Harare, Maputo)', 'value': 'Africa/Harare'},
  {'label': 'East Africa Time (Nairobi, Addis Ababa)', 'value': 'Africa/Nairobi'},
  {'label': 'South Africa Standard Time (Johannesburg)', 'value': 'Africa/Johannesburg'},
  {'label': 'Greenwich Mean Time (London, Dublin)', 'value': 'Europe/London'},
  {'label': 'Central European Time (Paris, Berlin, Rome)', 'value': 'Europe/Paris'},
  {'label': 'Eastern European Time (Athens, Cairo)', 'value': 'Europe/Athens'},
  {'label': 'Moscow Standard Time (Moscow)', 'value': 'Europe/Moscow'},
  {'label': 'Gulf Standard Time (Dubai, Muscat)', 'value': 'Asia/Dubai'},
  {'label': 'India Standard Time (Mumbai, Delhi)', 'value': 'Asia/Kolkata'},
  {'label': 'China Standard Time (Beijing, Shanghai)', 'value': 'Asia/Shanghai'},
  {'label': 'Japan Standard Time (Tokyo)', 'value': 'Asia/Tokyo'},
  {'label': 'Australian Eastern Standard Time (Sydney, Melbourne)', 'value': 'Australia/Sydney'},
  {'label': 'Eastern Time (New York, Washington DC)', 'value': 'America/New_York'},
  {'label': 'Central Time (Chicago, Mexico City)', 'value': 'America/Chicago'},
  {'label': 'Mountain Time (Denver, Phoenix)', 'value': 'America/Denver'},
  {'label': 'Pacific Time (Los Angeles, Vancouver)', 'value': 'America/Los_Angeles'},
  {'label': 'Brasilia Time (Sao Paulo, Rio)', 'value': 'America/Sao_Paulo'},
];
